"""Generate tool description overrides from OpenAPI specs.

Reads all enabled API spec files and produces a SQL migration that seeds
the tool_description_overrides table with rich, LLM-friendly descriptions.
"""

import json
import os
import sys
from pathlib import Path
from typing import Optional

SPECS = [
    ("fmc", "fmc_oas3.json", "Cisco FMC API"),
]

SPECS_DIR = Path(__file__).parent.parent / "openapi_specs"
OUTPUT = Path(__file__).parent.parent / "src" / "config" / "migrations" / "008_seed_tool_descriptions.sql"


def escape_sql(s: str) -> str:
    """Escape single quotes and newlines for PostgreSQL E'' strings."""
    if not s:
        return ""
    return s.replace("\\", "\\\\").replace("'", "''").replace("\n", "\\n")


def build_description(operation: dict, method: str, path: str) -> Optional[str]:
    """Build a concise LLM-friendly description from an OpenAPI operation."""
    desc = operation.get("description", "")
    summary = operation.get("summary", "")

    # Use description if available, else summary
    main = desc or summary
    if not main:
        return None

    # Truncate overly long descriptions
    if len(main) > 300:
        main = main[:297] + "..."

    parts = [main.strip()]

    # Add key parameter names (skip empty/unnamed params)
    params = operation.get("parameters", [])
    if params:
        param_names = []
        for p in params:
            name = p.get("name", "").strip()
            if not name:
                continue
            required = p.get("required", False)
            p_in = p.get("in", "")
            if p_in == "path" or required:
                param_names.append(f"{name} (required)")
            else:
                param_names.append(name)
        if param_names:
            parts.append("Params: " + ", ".join(param_names[:8]))

    # Note request body
    request_body = operation.get("requestBody", {})
    if request_body:
        content = request_body.get("content", {})
        json_content = content.get("application/json", {})
        schema = json_content.get("schema", {})
        props = schema.get("properties", {})
        if props:
            prop_names = list(props.keys())[:6]
            parts.append("Body fields: " + ", ".join(prop_names))

    return "\n".join(parts)


def main():
    sql_lines = []
    sql_lines.append("-- Migration 008: Seed tool description overrides from OpenAPI specs")
    sql_lines.append("-- Auto-generated by scripts/generate_tool_descriptions.py")
    sql_lines.append("-- Provides LLM-friendly descriptions for all FMC operations\n")

    counts = {}

    for api_name, spec_file, display_name in SPECS:
        spec_path = SPECS_DIR / spec_file
        if not spec_path.exists():
            print(f"WARNING: {spec_path} not found, skipping")
            continue

        with open(spec_path) as f:
            spec = json.load(f)

        paths = spec.get("paths", {})
        api_count = 0

        for path, methods in paths.items():
            for method, operation in methods.items():
                if method in ("parameters", "summary", "description", "servers"):
                    continue
                if not isinstance(operation, dict):
                    continue

                operation_id = operation.get("operationId")
                if not operation_id:
                    continue

                tool_name = f"{api_name}_{operation_id}"
                # MCP tool names are max 64 chars
                if len(tool_name) > 64:
                    tool_name = operation_id[:64]

                desc = build_description(operation, method.upper(), path)
                if not desc:
                    continue

                escaped_name = escape_sql(tool_name)
                escaped_desc = escape_sql(desc)

                sql_lines.append(
                    f"INSERT INTO tool_description_overrides (operation_name, enhanced_description, is_active) "
                    f"VALUES ('{escaped_name}', E'{escaped_desc}', true) "
                    f"ON CONFLICT (operation_name) DO UPDATE SET "
                    f"enhanced_description = EXCLUDED.enhanced_description, "
                    f"updated_at = NOW();"
                )
                api_count += 1

        counts[api_name] = api_count
        print(f"{display_name}: {api_count} descriptions generated")

    # Write output
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT, "w") as f:
        f.write("\n".join(sql_lines) + "\n")

    total = sum(counts.values())
    print(f"\nTotal: {total} tool descriptions written to {OUTPUT}")


if __name__ == "__main__":
    main()
